# Generated by Django 5.0.3 on 2024-04-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_prd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prd',
            old_name='pri',
            new_name='prd',
        ),
    ]
